name: InvisibleArmor
version: 1.2
main: com.janmaki.mqrimo.invisible_armor.Main
author: Pro_Snape (fork by janmaki)
api-version: 1.13

commands:
  invArmor:
    description: /invArmor <args...>

permissions:
  invArmor.*:
    default: false
  invArmor.command.*:
    default: false
  invArmor.command.toggle:
    default: false