name: InvisibleArmor
version: 1.2
main: com.janmaki.mqrimo.invisible_armor.Main
author: JanMaki
api-version: 1.13

commands:
  invArmor:
    description: /invArmor <args...>

permissions:
  invArmor.*:
    default: op
  invArmor.all:
    default: true
  invArmor.me:
    default: true
  invArmor.reset:
    default: true
  invArmor.player:
    default: true
  invArmor.list:
    default: true